#!/bin/sh

# Compile your own programs in your own directory
# script_name :  compileRFID
# version 1.0 / marcus / 2018

# To use type  ./compileRFID program
# Do NOT add ".c" that will be added by the script.  
# An executable with the programname will be created in  directory. 


# The include directory contains the .h files needed

include="/home/pi/MercuryApi-Using-C/Mercury_rfid/mercuryapi-1.29.4.34/c/src/api"


option="-D TMR_ENABLE_SERIAL_READER_ONLY=1 -g -fPIC"



# Want clean and good code, hence extra checks

checks="-Werror -Wall"

cc $option -I $include $checks -o $1 $1.c -lmercuryapi -lreadline -lpthread
